spring.application.name=movies

spring.datasource.url=jdbc:h2:mem:dbmovie
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=admin
spring.datasource.password=admin

spring.h2.console.enabled=true
spring.h2.console.path=/h2

spring.jpa.hibernate.ddl-auto=create
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.defer-datasource-initialization=true

outsera.challenge.csv.location=/opt/Movielist.csv
outsera.challenge.csv.producer.names.splitter.regex=,|\\sand\\s
